### PR TITLE
HIVE-28666: Migrate documentation from the wiki to the website

### PR DESCRIPTION
**Pull request by zabetak**

### CODE REVIEW

**Review by okumin — APPROVED** [review]
This is the great step to modernize our resources.

**Comment by simhadri-g** [comment]
Thanks @zabetak , this is really great. I will try build this and see if i can host it on github pages :)

**Comment by simhadri-g** [comment]
I have deployed it with github pages here: https://simhadri-g.github.io/hive-site/docs/latest/  
This is really great start, we can incrementally improve the docs from here :)

**Review by simhadri-g — APPROVED** [review]
LGTM

**Review by zhangbutao — APPROVED** [review]
+1

**Comment by zhangbutao** [comment]
A great start! Thanks @zabetak 
It seems that there are many details that need to be continuously refined. Such as font size, color, title, multi-version document, etc. But we can improve this gradually. I hope we can attract new contributors to improve the web-site.

**Pull request closed without merging**
